### ISSUE TITLE
Ecrire une description du projet

### ISSUE THREAD

**Issue by vfabry** [geo2france/template-dashboard#1]
ça facilitera la compréhension du dépôt

**Comment by jbdesbas** [comment]
:question: 
![image](https://github.com/geo2france/template-dashboard/assets/6163107/909ea37b-0176-4773-ad1f-2fd6a4ec793f)

**Comment by MaximeGuillemin** [comment]
![Capture d’écran 2024-04-19 094639](https://github.com/geo2france/template-dashboard/assets/114729400/8fd2b2f4-8f13-4a8f-91d1-177feac41176)
